sudo: false
language: python
python:
- '3.5'
services:
- docker
before_install:
- docker build -t antlr_tsql .
script: docker run -v $(pwd):/usr/src/app antlr_tsql make build test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: MPWPgWOSiN5A4cKjzQ9+9QDjkYXi/+IYnB4UuC+Btyhig6vfdo0SYb57SHVx/8RApenn5S1p5sziT7MNCyiapw1UgB8rVq+zEsENxoZ+Qg85IIu/kFXVa+mYxYDfLVw8zotYfkp0Ca1sYUXRYrQnjkz6ApYZi++9Wkol4+Ea6P8S9FiAVWpCOuKsIwxmYMZ09Ub0q/15Vd3h4EKYoVhOgX3xDPK9gHMjx950mQSmJagTEAVqb5NHzw9EW9rEarYtjd+LGdW04xHh6SsXYBvNJqkJmu3gy4NAcLb8HEY+uqR25+7Fkdxcd7rv1nq6ZiK8uCUcVG2u+OFjCuFhQk5t9p/KOceqFueb/Xxgbu+21m+zUXpD7yrJWrTue6Iy4BxF0V+5cZmkfZFJNd/TiGZcNLjmSTIr8iqdd3eKShpzdNXUZ+TzJPjs94jMIJ+5j2lDZb3WWf1365tRv8Kr2/zA7b8mVjn4EyRTE1hMYgNwh7t62Co8QtR/x7pKKHL0XRsWyovwuM9ihFSgr9K5BxLeJTt01xz3y8UlKuE0s78ddJYaotrmHOPXeqFT/2d0urEQGMTpUCqWofL/BcdjihLXSU7AUXtHfqicVhiBvHxVeYarfzxbWwwWgKp0f6RwwFBFy8t98RIRk+Fts4PX6DEJ2gMD++gYyNK0A51dG/CQI7Q=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/antlr-tsql
  skip_cleanup: true
  skip_upload_docs: true
