sudo: false
language: python
services:
- docker
before_install:
- docker build -t antlr .
script: docker run -v $(pwd):/usr/src/app antlr make build test
after_script: ([ "${TRAVIS_BRANCH}" = "dev" ] || [ "${TRAVIS_BRANCH}" = "master" ])
  && docker run -e GH_TOKEN -e TRAVIS_BRANCH -e TRAVIS_TAG -e TRAVIS_COMMIT antlr
  make clean deploy
deploy:
  provider: pypi
  user: machow
  password:
    secure: rO6uB11S7nyT7YjicTImY5zgvFQZlCrWUcPPDB/DFj3pWANKyxNZ3QoaIXl/j/7P8p9QsRiPvWcqxNae7QAIsvoiM2dQLzLKNLMQy4s6/B1fG1xWQLc6LAPzVlqFCAnm9CNFGSnMn1t4oeCvCmkycZczp1yZwPLBeQpK2gFg0cNdt042ntoklRTAjAJLvThwtjiXVsUEQ8ZZ7QV3RIjFHNzrgje+yWV//uEfsmekIk6i1u/ypImiPxnjut53d15Qs8UQTFg/XmTml6xx2gRgmSAYeFpONlPM528b0OauWSE9jwu07i88FUwuEm6OefiCugmpaj/SDpsEZKl/ecjYgZV9pDWpRvg6WPRWLaZ6gnA7zDQvrT8x0nEQRMOQfNjAPqvUCgEy5R8vZ9NoFr879GC56Ca9KUZeoqwkJMooeQfZLy3uJLFFYwVmT3DVrnUit3PwXLSkSu1VFMXzBV/Z5kOSoCGzFvvmTOGQvzC8Fs1+lXwMeUl1K8CT8arIKpg+BN/FzFmEzuH+xG29w1LoQxcy40CBvinOKTmtlowYwWws1PITOJPHQmVxWXU7i1rNXpoRzeSceGI3dTvWtXwSZre5Y/nfNHBENuX1O1Y7CMROeeMxp+tgbhstpiZSMHli9cNRHAgHJ8uP7ujlAW3vfgGT3glBxpSEoXWvhKvY3eA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/antlr-tsql
  skip_cleanup: true
  skip_upload_docs: true
