sudo: false
language: python
python:
- '3.5'
services:
- docker
before_install:
- docker build -t antlr_tsql .
script: docker run -v $(pwd):/usr/src/app antlr_tsql make build test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: taxW1I1oTRK5auofkYdQDJ2shm9vLRaOu5dpm/pWaVUNLahLKSUOPchJB+w4erPqlpIzjr5kkkxyJmCbyuycL79k3oHwTy8H+bPp69LXNv2i2EiiI9BdEuUzvooJQSm7Bqcl2Fh3/s8CiewgbogMaHt6TYt4yWUWzQjsd67qDUSmLDs1iCTsFYAgywiFP1+iFUqoHtqKFDzzceQWJDjcUFJblawr9XcuI4mNupyBjs2RlBqftlN9WVKn+wDnXlsGs9IGIkggCQ/26wNrDP5OCCkTj6TFQPP52axW/iBWe//zW5CMFPahDwTnKdT5xyIL2yVwgb/WamUzKvgR/ZoWVZ5kvfsExxAZKdAaD7MUlFL2YwGUDbrXefkpkdet35cYeD/vRtWLpBDGamrICkxX71wjyBeDZzj1irZxLuiJC0nTbyYTcJr6N/NFwbfaq2HcduKA8jRv5fKdzebwBmhAhetE0OXtBA1HZ5NOCe8SkMLe63lJWxiPMVoMbA7XeLtAlh8E/xnK7g2NjDCDRXs8zAJjK2JWuBUWCzeqKXroV8s7MkQwS5wlPIMpKbGPunAGfyG8qhc1ClqOVkXRnDflLwwD5m7Uxf2cIenT5bro4dNMSw8xE3XYyBkZzgbOBo4GHd1PpmkUaDA7Jpw3crQW1Tf0chI5rL8DszRPC4fJisQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/antlr-tsql
  skip_cleanup: true
  skip_upload_docs: true
