sudo: false
language: python
python:
- '3.5'
services:
- docker
before_install:
- docker build -t antlr_tsql .
script: docker run -v $(pwd):/usr/src/app antlr_tsql make build test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: FtfGuRIwye1Va1uU4iOgESpRl5FSxbhi6hqQ/4QIhyZdpr8+YJrjRw8LbiSpPKCgQBXwN37Xif16k2ySEearae0pGmB7Kg8FXpo9VubNBtcUyfa0EmJAVGQRgjFFz90nvB75UvV5r8QMSVq9erZjZ36VR+OqKb/GdiZVDDygktIEGTJkR3pS0Hzwy5UfpuTpnGIMRDDrGBQKcLqXKCUa3uytXttul7BwP0wrhvnpEdCAN/LMUS+K0fWweBwrd3zQ5f6Ee3HrZpXrX5d5sE7TxSwhz4/o20I0nE21q78gjvoDziEKOxP96aNEeWTGgdRUljIm+Hv0rsV6FcURnGLfqmHdynM5mcrAF9KS39i19jZPVzDK4r/HhsfN+3E+ZVubOsjXcunwhTDXWqpoNuxExzBE2Gw8HJ9BEf9PJZ3bQH61FiKoaiOHgfOccH3E20zOkEjG6X9pKdHzUF0DcxKnntv5D1kGMhsAO8dm3/cV7xJiu8fjgn3tzPOVzxXG3Wxc7w/icL/MMCUFrfNRZG8NWY82GGJB3qwBkIRoSiYWtcz1BMwUIo4kPU/AqRlhetrlWAP/StJ3walREgrk14snTwT6MzrHspNwbhWRaoNJzVa4dAlN1cnAL7KAoJVPEtca/gW6CFlBD1JlY11PXVjHCdVdk78UDrUszHZig4w7dEA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/antlr-tsql
  skip_cleanup: true
  skip_upload_docs: true
